import "./globals.css";

export const metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <title>CSR Sample</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
